import React, { useState, useEffect, useCallback, useRef } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import './App.css';

const API = 'http://localhost:8080/api/meetings';

const TRANSLATIONS = {
  de: {
    dashboard: 'Dashboard', meetings: 'Meetings', tasks: 'Aufgaben',
    calendar: 'Kalender', archive: 'Archiv', settings: 'Einstellungen',
    darkMode: 'Dunkelmodus', lightMode: 'Hellmodus',
    newMeeting: 'Neues Meeting', save: 'Speichern', cancel: 'Abbrechen',
    analyze: 'KI-Analyse starten', analyzing: 'Analyse läuft...',
    edit: 'Bearbeiten', delete: 'Löschen', export: 'PDF Export', copy: 'Kopieren',
    noMeetingSelected: 'Kein Meeting ausgewählt',
    noMeetingHint: 'Wähle ein Meeting aus der Liste oder drücke N für ein neues Meeting.',
    protocol: 'Protokoll', aiSummary: 'KI-Zusammenfassung', geminiLabel: 'Generiert von Google Gemini',
    participants: 'Teilnehmer', detectedTasks: 'Erkannte Aufgaben',
    searchPlaceholder: 'Titel, Protokoll oder Ort...',
    allMeetings: 'Alle', analyzed: 'Analysiert', open: 'Offen', draft: 'Entwurf',
    sortNewest: 'Datum (neueste)', sortOldest: 'Datum (älteste)',
    sortTitleAZ: 'Titel (A-Z)', sortTitleZA: 'Titel (Z-A)',
    status: 'Status', sorting: 'Sortierung', resetFilter: 'Filter zurücksetzen',
    noMeetingsFound: 'Keine Meetings gefunden.', noMeetingsYet: 'Noch keine Meetings vorhanden.',
    totalMeetings: 'Meetings gesamt', aiAnalyzed: 'KI-analysiert',
    tasksDone: 'Aufgaben erledigt', recentMeetings: 'Letzte Meetings',
    tasksOverview: 'Aufgaben-Übersicht', allTasks: 'Alle', openTasks: 'Offen', doneTasks: 'Erledigt',
    noTasksYet: 'Starte eine KI-Analyse um Aufgaben zu erkennen.',
    titleLabel: 'Titel *', locationLabel: 'Ort', dateLabel: 'Datum & Uhrzeit',
    participantsLabel: 'Teilnehmer', protocolLabel: 'Protokolltext',
    titlePlaceholder: 'z.B. Sprint Planning Q3', locationPlaceholder: 'z.B. Konferenzraum A',
    protocolPlaceholder: 'Was wurde besprochen? Wer übernimmt was?',
    participantPlaceholder: 'Name eingeben...',
    editMeeting: 'Meeting bearbeiten', editSub: 'Ändere die Details dieses Meetings',
    newMeetingSub: 'Erstelle ein neues Meeting und erfasse das Protokoll',
    dictation: 'Diktat', stop: 'Stopp', recording: 'Aufnahme läuft — sprich jetzt...',
    copied: 'Zusammenfassung in Zwischenablage kopiert.',
    meetingCreated: 'Meeting erfolgreich erstellt.',
    meetingUpdated: 'Meeting erfolgreich aktualisiert.',
    meetingDeleted: 'Meeting wurde gelöscht.',
    analysisSuccess: 'KI-Analyse erfolgreich abgeschlossen.',
    analysisFailed: 'KI-Analyse fehlgeschlagen. Bitte später erneut versuchen.',
    connectionFailed: 'Verbindung zum Server fehlgeschlagen.',
    saveFailed: 'Fehler beim Speichern.',
    confirmDelete: 'Meeting wirklich löschen?',
    statusSet: 'Status auf', statusSet2: 'gesetzt.',
    meetingsPerWeek: 'Meetings pro Woche', weekLabel: 'KW',
    language: 'Sprache', cancelEsc: 'Abbrechen (Esc)',
    calendarSub: 'Monats- und Jahresansicht deiner Meetings',
    monthView: 'Monat', yearView: 'Jahr',
    meetingsOnDay: 'Meetings am', noMeetingsOnDay: 'Keine Meetings an diesem Tag.',
    selectDay: 'Tag auswählen um Meetings zu sehen',
  },
  en: {
    dashboard: 'Dashboard', meetings: 'Meetings', tasks: 'Tasks',
    calendar: 'Calendar', archive: 'Archive', settings: 'Settings',
    darkMode: 'Dark Mode', lightMode: 'Light Mode',
    newMeeting: 'New Meeting', save: 'Save', cancel: 'Cancel',
    analyze: 'Start AI Analysis', analyzing: 'Analyzing...',
    edit: 'Edit', delete: 'Delete', export: 'PDF Export', copy: 'Copy',
    noMeetingSelected: 'No meeting selected',
    noMeetingHint: 'Select a meeting from the list or press N to create a new one.',
    protocol: 'Protocol', aiSummary: 'AI Summary', geminiLabel: 'Generated by Google Gemini',
    participants: 'Participants', detectedTasks: 'Detected Tasks',
    searchPlaceholder: 'Title, protocol or location...',
    allMeetings: 'All', analyzed: 'Analyzed', open: 'Open', draft: 'Draft',
    sortNewest: 'Date (newest)', sortOldest: 'Date (oldest)',
    sortTitleAZ: 'Title (A-Z)', sortTitleZA: 'Title (Z-A)',
    status: 'Status', sorting: 'Sorting', resetFilter: 'Reset filter',
    noMeetingsFound: 'No meetings found.', noMeetingsYet: 'No meetings yet.',
    totalMeetings: 'Total meetings', aiAnalyzed: 'AI analyzed',
    tasksDone: 'Tasks done', recentMeetings: 'Recent Meetings',
    tasksOverview: 'Tasks Overview', allTasks: 'All', openTasks: 'Open', doneTasks: 'Done',
    noTasksYet: 'Start an AI analysis to detect tasks.',
    titleLabel: 'Title *', locationLabel: 'Location', dateLabel: 'Date & Time',
    participantsLabel: 'Participants', protocolLabel: 'Protocol Text',
    titlePlaceholder: 'e.g. Sprint Planning Q3', locationPlaceholder: 'e.g. Conference Room A',
    protocolPlaceholder: 'What was discussed? Who takes over what?',
    participantPlaceholder: 'Enter name...',
    editMeeting: 'Edit Meeting', editSub: 'Change the details of this meeting',
    newMeetingSub: 'Create a new meeting and capture the protocol',
    dictation: 'Dictate', stop: 'Stop', recording: 'Recording — speak now...',
    copied: 'Summary copied to clipboard.',
    meetingCreated: 'Meeting created successfully.',
    meetingUpdated: 'Meeting updated successfully.',
    meetingDeleted: 'Meeting deleted.',
    analysisSuccess: 'AI analysis completed successfully.',
    analysisFailed: 'AI analysis failed. Please try again later.',
    connectionFailed: 'Connection to server failed.',
    saveFailed: 'Error saving.',
    confirmDelete: 'Really delete this meeting?',
    statusSet: 'Status set to', statusSet2: '.',
    meetingsPerWeek: 'Meetings per week', weekLabel: 'CW',
    language: 'Language', cancelEsc: 'Cancel (Esc)',
    calendarSub: 'Monthly and yearly view of your meetings',
    monthView: 'Month', yearView: 'Year',
    meetingsOnDay: 'Meetings on', noMeetingsOnDay: 'No meetings on this day.',
    selectDay: 'Select a day to see meetings',
  }
};

const NAV_ITEMS = [
  { id: 'dashboard', icon: 'M3 13h8V3H3v10zm0 8h8v-6H3v6zm10 0h8V11h-8v10zm0-18v6h8V3h-8z' },
  { id: 'meetings', icon: 'M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z' },
  { id: 'tasks', icon: 'M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z' },
  { id: 'calendar', icon: 'M20 3h-1V1h-2v2H7V1H5v2H4c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 18H4V8h16v13z' },
  { id: 'archive', icon: 'M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM12 17.5L6.5 12H10v-2h4v2h3.5L12 17.5zM5.12 5l.81-1h12l.94 1H5.12z' },
  { id: 'settings', icon: 'M19.14,12.94c0.04-0.3,0.06-0.61,0.06-0.94c0-0.32-0.02-0.64-0.07-0.94l2.03-1.58c0.18-0.14,0.23-0.41,0.12-0.61 l-1.92-3.32c-0.12-0.22-0.37-0.29-0.59-0.22l-2.39,0.96c-0.5-0.38-1.03-0.7-1.62-0.94L14.4,2.81c-0.04-0.24-0.24-0.41-0.48-0.41 h-3.84c-0.24,0-0.43,0.17-0.47,0.41L9.25,5.35C8.66,5.59,8.12,5.92,7.63,6.29L5.24,5.33c-0.22-0.08-0.47,0-0.59,0.22L2.74,8.87 C2.62,9.08,2.66,9.34,2.86,9.48l2.03,1.58C4.84,11.36,4.8,11.69,4.8,12s0.02,0.64,0.07,0.94l-2.03,1.58 c-0.18,0.14-0.23,0.41-0.12,0.61l1.92,3.32c0.12,0.22,0.37,0.29,0.59,0.22l2.39-0.96c0.5,0.38,1.03,0.7,1.62,0.94l0.36,2.54 c0.05,0.24,0.24,0.41,0.48,0.41h3.84c0.24,0,0.44-0.17,0.47-0.41l0.36-2.54c0.59-0.24,1.13-0.56,1.62-0.94l2.39,0.96 c0.22,0.08,0.47,0,0.59-0.22l1.92-3.32c0.12-0.22,0.07-0.47-0.12-0.61L19.14,12.94z M12,15.6c-1.98,0-3.6-1.62-3.6-3.6 s1.62-3.6,3.6-3.6s3.6,1.62,3.6,3.6S13.98,15.6,12,15.6z' },
];

const STATUS_OPTIONS = ['OFFEN', 'IN_BEARBEITUNG', 'ABGESCHLOSSEN'];

const ONBOARDING_STEPS = (t) => [
  { title: t.dashboard === 'Dashboard' ? 'Willkommen bei MeetingMind' : 'Welcome to MeetingMind', desc: t.dashboard === 'Dashboard' ? 'Das KI-gestützte Tool für professionelle Meeting-Protokolle. Erstelle, verwalte und analysiere deine Meetings mit Google Gemini AI.' : 'The AI-powered tool for professional meeting protocols. Create, manage and analyze your meetings with Google Gemini AI.', hint: t.dashboard === 'Dashboard' ? 'Schritt 1 von 3' : 'Step 1 of 3' },
  { title: t.dashboard === 'Dashboard' ? 'Meetings erstellen & verwalten' : 'Create & manage meetings', desc: t.dashboard === 'Dashboard' ? 'Lege neue Meetings an, erfasse den Protokolltext und behalte den Überblick über alle vergangenen Besprechungen.' : 'Create new meetings, capture protocol text and keep track of all past discussions.', hint: t.dashboard === 'Dashboard' ? 'Schritt 2 von 3' : 'Step 2 of 3' },
  { title: t.dashboard === 'Dashboard' ? 'KI-Analyse starten' : 'Start AI Analysis', desc: t.dashboard === 'Dashboard' ? 'Mit einem Klick analysiert Google Gemini dein Protokoll und erstellt automatisch eine Zusammenfassung sowie eine Liste erkannter Aufgaben.' : 'With one click, Google Gemini analyzes your protocol and automatically creates a summary and a list of detected tasks.', hint: t.dashboard === 'Dashboard' ? 'Schritt 3 von 3' : 'Step 3 of 3' },
];

function Icon({ path, size = 18, color = 'currentColor' }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill={color}><path d={path} /></svg>;
}

function Toast({ message, type, onClose }) {
  useEffect(() => { const t = setTimeout(onClose, 3500); return () => clearTimeout(t); }, [onClose]);
  return (
    <div className={`toast toast-${type}`}>
      <span>{message}</span>
      <button onClick={onClose} className="toast-close">×</button>
    </div>
  );
}

function StatusBadge({ meeting, t }) {
  if (meeting.aiSummary) return <span className="badge badge-analyzed">{t.analyzed}</span>;
  if (meeting.protocolText) return <span className="badge badge-open">{t.open}</span>;
  return <span className="badge badge-draft">{t.draft}</span>;
}

function groupMeetingsByDate(meetings, t) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const weekAgo = new Date(today);
  weekAgo.setDate(today.getDate() - 7);
  const todayLabel = t.dashboard === 'Dashboard' ? 'Heute' : 'Today';
  const weekLabel = t.dashboard === 'Dashboard' ? 'Diese Woche' : 'This Week';
  const olderLabel = t.dashboard === 'Dashboard' ? 'Älter' : 'Older';
  const groups = { [todayLabel]: [], [weekLabel]: [], [olderLabel]: [] };
  meetings.forEach(m => {
    const d = new Date(m.meetingDate);
    d.setHours(0, 0, 0, 0);
    if (d.getTime() === today.getTime()) groups[todayLabel].push(m);
    else if (d >= weekAgo) groups[weekLabel].push(m);
    else groups[olderLabel].push(m);
  });
  return groups;
}

function applyFilterAndSort(meetings, search, filter, sort) {
  let result = [...meetings];
  if (search) {
    const q = search.toLowerCase();
    result = result.filter(m =>
      m.title.toLowerCase().includes(q) ||
      (m.protocolText && m.protocolText.toLowerCase().includes(q)) ||
      (m.location && m.location.toLowerCase().includes(q))
    );
  }
  if (filter === 'analyzed') result = result.filter(m => m.aiSummary);
  if (filter === 'open') result = result.filter(m => m.protocolText && !m.aiSummary);
  if (filter === 'draft') result = result.filter(m => !m.protocolText);
  result.sort((a, b) => {
    if (sort === 'date-desc') return new Date(b.meetingDate) - new Date(a.meetingDate);
    if (sort === 'date-asc') return new Date(a.meetingDate) - new Date(b.meetingDate);
    if (sort === 'title-asc') return a.title.localeCompare(b.title);
    if (sort === 'title-desc') return b.title.localeCompare(a.title);
    return 0;
  });
  return result;
}

async function exportToPDF(meeting) {
  const element = document.getElementById('export-content');
  element.classList.add('exporting');
  const canvas = await html2canvas(element, { scale: 2, useCORS: true });
  element.classList.remove('exporting');
  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF('p', 'mm', 'a4');
  const width = pdf.internal.pageSize.getWidth();
  const height = (canvas.height * width) / canvas.width;
  pdf.addImage(imgData, 'PNG', 0, 0, width, height);
  pdf.save(`${meeting.title.replace(/\s+/g, '_')}_Protokoll.pdf`);
}

function useSpeechRecognition(onTranscript, lang) {
  const recognitionRef = useRef(null);
  const [listening, setListening] = useState(false);
  const [supported, setSupported] = useState(false);
  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SpeechRecognition) {
      setSupported(true);
      const recognition = new SpeechRecognition();
      recognition.lang = lang === 'en' ? 'en-US' : 'de-DE';
      recognition.continuous = true;
      recognition.interimResults = true;
      recognition.onresult = (e) => {
        let final = '';
        for (let i = e.resultIndex; i < e.results.length; i++) {
          if (e.results[i].isFinal) final += e.results[i][0].transcript + ' ';
        }
        if (final) onTranscript(final);
      };
      recognition.onend = () => setListening(false);
      recognitionRef.current = recognition;
    }
  }, [lang]);
  const startListening = () => { if (recognitionRef.current && !listening) { recognitionRef.current.start(); setListening(true); } };
  const stopListening = () => { if (recognitionRef.current && listening) { recognitionRef.current.stop(); setListening(false); } };
  return { listening, supported, startListening, stopListening };
}

function SplashScreen({ onDone }) {
  useEffect(() => { const t = setTimeout(onDone, 2200); return () => clearTimeout(t); }, [onDone]);
  return (
    <div className="splash-screen">
      <div className="splash-content">
        <div className="splash-logo"><div className="splash-logo-mark">M</div></div>
        <div className="splash-name">MeetingMind</div>
        <div className="splash-tagline">KI-gestützte Meeting-Protokolle</div>
        <div className="splash-bar"><div className="splash-bar-fill" /></div>
      </div>
    </div>
  );
}

function OnboardingScreen({ onFinish, t }) {
  const [step, setStep] = useState(0);
  const steps = ONBOARDING_STEPS(t);
  const current = steps[step];
  const isLast = step === steps.length - 1;
  return (
    <div className="onboarding-overlay">
      <div className="onboarding-card">
        <div className="onboarding-logo"><div className="logo-mark" style={{ width: 48, height: 48, fontSize: 22, borderRadius: 12 }}>M</div></div>
        <div className="onboarding-hint">{current.hint}</div>
        <h2 className="onboarding-title">{current.title}</h2>
        <p className="onboarding-desc">{current.desc}</p>
        <div className="onboarding-dots">{steps.map((_, i) => <div key={i} className={`onboarding-dot ${i === step ? 'active' : ''}`} />)}</div>
        <div className="onboarding-actions">
          {step > 0 && <button className="btn-onboard-back" onClick={() => setStep(s => s - 1)}>{t.dashboard === 'Dashboard' ? 'Zurück' : 'Back'}</button>}
          <button className="btn-onboard-next" onClick={() => isLast ? onFinish() : setStep(s => s + 1)}>
            {isLast ? (t.dashboard === 'Dashboard' ? 'Loslegen' : 'Get started') : (t.dashboard === 'Dashboard' ? 'Weiter' : 'Next')}
          </button>
        </div>
        <button className="onboarding-skip" onClick={onFinish}>{t.dashboard === 'Dashboard' ? 'Überspringen' : 'Skip'}</button>
      </div>
    </div>
  );
}

function ShortcutsModal({ onClose, t }) {
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h3>{t.dashboard === 'Dashboard' ? 'Tastaturkürzel' : 'Keyboard Shortcuts'}</h3>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>
        <div className="shortcuts-list">
          {[
            { key: 'N', desc: t.newMeeting },
            { key: 'D', desc: t.dashboard },
            { key: 'M', desc: t.meetings },
            { key: 'T', desc: t.tasks },
            { key: 'K', desc: t.calendar },
            { key: 'L', desc: t.language },
            { key: 'Esc', desc: t.dashboard === 'Dashboard' ? 'Formular / Modal schließen' : 'Close form / modal' },
            { key: '?', desc: t.dashboard === 'Dashboard' ? 'Diese Übersicht' : 'This overview' },
          ].map(s => (
            <div key={s.key} className="shortcut-row">
              <kbd className="kbd">{s.key}</kbd>
              <span>{s.desc}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function Sidebar({ activeNav, setActiveNav, onNewMeeting, darkMode, setDarkMode, sidebarOpen, setSidebarOpen, t, lang, setLang }) {
  return (
    <>
      {sidebarOpen && <div className="sidebar-backdrop" onClick={() => setSidebarOpen(false)} />}
      <div className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}>
        <div className="sidebar-logo">
          <div className="logo-mark">M</div>
          <span className="logo-name">MeetingMind</span>
        </div>
        <nav className="sidebar-nav">
          {NAV_ITEMS.map(item => (
            <button key={item.id} className={`nav-item ${activeNav === item.id ? 'active' : ''}`}
              onClick={() => { setActiveNav(item.id); setSidebarOpen(false); }}>
              <Icon path={item.icon} size={17} />
              <span className="nav-label">{t[item.id]}</span>
            </button>
          ))}
        </nav>
        <div className="sidebar-bottom">
          <button className="dark-toggle" onClick={() => setLang(l => l === 'de' ? 'en' : 'de')}>
            <span style={{ fontSize: 16 }}>{lang === 'de' ? '🇩🇪' : '🇬🇧'}</span>
            <span className="nav-label">{lang === 'de' ? 'English' : 'Deutsch'}</span>
          </button>
          <button className="dark-toggle" onClick={() => setDarkMode(d => !d)}>
            <span className="dark-toggle-icon">{darkMode ? '○' : '●'}</span>
            <span className="nav-label">{darkMode ? t.lightMode : t.darkMode}</span>
          </button>
          <div className="user-profile">
            <div className="user-avatar">SB</div>
            <div className="user-info">
              <span className="user-name">Suayb B.</span>
              <span className="user-role">Administrator</span>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

function WeeklyChart({ meetings, t }) {
  const weeks = {};
  meetings.forEach(m => {
    const d = new Date(m.meetingDate);
    const year = d.getFullYear();
    const week = Math.ceil(((d - new Date(year, 0, 1)) / 86400000 + new Date(year, 0, 1).getDay() + 1) / 7);
    const key = `${t.weekLabel} ${week}`;
    weeks[key] = (weeks[key] || 0) + 1;
  });
  const entries = Object.entries(weeks).slice(-6);
  const max = Math.max(...entries.map(([, v]) => v), 1);
  if (entries.length === 0) return <div className="chart-empty"><p>{t.dashboard === 'Dashboard' ? 'Noch keine Daten für das Diagramm.' : 'No data for the chart yet.'}</p></div>;
  return (
    <div className="weekly-chart">
      <div className="chart-bars">
        {entries.map(([label, count]) => (
          <div key={label} className="chart-bar-col">
            <span className="chart-bar-value">{count}</span>
            <div className="chart-bar-track"><div className="chart-bar-fill" style={{ height: `${(count / max) * 100}%` }} /></div>
            <span className="chart-bar-label">{label}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function Dashboard({ meetings, t }) {
  const analyzed = meetings.filter(m => m.aiSummary).length;
  const open = meetings.filter(m => m.protocolText && !m.aiSummary).length;
  const totalTasks = meetings.reduce((sum, m) => sum + (m.tasks?.length || 0), 0);
  const doneTasks = meetings.reduce((sum, m) => sum + (m.tasks?.filter(t2 => t2.done)?.length || 0), 0);
  return (
    <div className="detail-panel fade-in">
      <div className="detail-header">
        <div><h2>{t.dashboard}</h2><p className="detail-sub">{t.dashboard === 'Dashboard' ? 'Übersicht aller Meeting-Aktivitäten' : 'Overview of all meeting activities'}</p></div>
      </div>
      <div className="detail-body">
        <div className="stats-grid">
          <div className="stat-card"><span className="stat-value">{meetings.length}</span><span className="stat-label">{t.totalMeetings}</span><div className="stat-bar" style={{ width: '100%' }} /></div>
          <div className="stat-card"><span className="stat-value">{analyzed}</span><span className="stat-label">{t.aiAnalyzed}</span><div className="stat-bar green" style={{ width: meetings.length ? `${(analyzed / meetings.length) * 100}%` : '0%' }} /></div>
          <div className="stat-card"><span className="stat-value">{open}</span><span className="stat-label">{t.open}</span><div className="stat-bar amber" style={{ width: meetings.length ? `${(open / meetings.length) * 100}%` : '0%' }} /></div>
          <div className="stat-card"><span className="stat-value">{doneTasks}/{totalTasks}</span><span className="stat-label">{t.tasksDone}</span><div className="stat-bar blue" style={{ width: totalTasks ? `${(doneTasks / totalTasks) * 100}%` : '0%' }} /></div>
        </div>
        <div className="detail-section">
          <h3 className="section-title">{t.meetingsPerWeek}</h3>
          <div className="chart-card"><WeeklyChart meetings={meetings} t={t} /></div>
        </div>
        <div className="detail-section">
          <h3 className="section-title">{t.recentMeetings}</h3>
          {meetings.length === 0 ? (
            <div className="empty-state-inline">
              <div className="empty-icon-box" style={{ margin: '0 auto 12px' }}>📅</div>
              <h3>{t.dashboard === 'Dashboard' ? 'Keine Meetings vorhanden' : 'No meetings yet'}</h3>
              <p>{t.dashboard === 'Dashboard' ? 'Erstelle dein erstes Meeting mit dem + Button.' : 'Create your first meeting with the + button.'}</p>
            </div>
          ) : meetings.slice(0, 5).map(m => (
            <div key={m.id} className="dashboard-meeting-row">
              <div className="dmr-left">
                <span className="dmr-title">{m.title}</span>
                <span className="dmr-meta">{m.location} · {new Date(m.meetingDate).toLocaleDateString(t.dashboard === 'Dashboard' ? 'de-DE' : 'en-US')}</span>
              </div>
              <StatusBadge meeting={m} t={t} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function TasksOverview({ meetings, onTaskToggle, t }) {
  const [taskFilter, setTaskFilter] = useState('all');
  const allTasks = meetings.flatMap(m => (m.tasks || []).map((task, i) => ({ ...task, meetingTitle: m.title, meetingId: m.id, taskIndex: i })));
  const filtered = allTasks.filter(task => { if (taskFilter === 'open') return !task.done; if (taskFilter === 'done') return task.done; return true; });
  const doneCount = allTasks.filter(task => task.done).length;
  return (
    <div className="detail-panel fade-in">
      <div className="detail-header">
        <div><h2>{t.tasksOverview}</h2><p className="detail-sub">{doneCount} {t.dashboard === 'Dashboard' ? 'von' : 'of'} {allTasks.length} {t.dashboard === 'Dashboard' ? 'Aufgaben erledigt' : 'tasks done'}</p></div>
        <div className="detail-actions">
          {[['all', t.allTasks], ['open', t.openTasks], ['done', t.doneTasks]].map(([f, label]) => (
            <button key={f} className={`filter-chip ${taskFilter === f ? 'active' : ''}`} style={{ padding: '8px 14px' }} onClick={() => setTaskFilter(f)}>{label}</button>
          ))}
        </div>
      </div>
      <div className="detail-body">
        {filtered.length === 0 && (
          <div className="empty-state-inline">
            <div className="empty-icon-box" style={{ margin: '0 auto 12px', fontSize: 24 }}>✓</div>
            <h3>{taskFilter === 'done' ? (t.dashboard === 'Dashboard' ? 'Noch nichts erledigt' : 'Nothing done yet') : (t.dashboard === 'Dashboard' ? 'Keine offenen Aufgaben' : 'No open tasks')}</h3>
            <p>{t.noTasksYet}</p>
          </div>
        )}
        <div className="task-list">
          {filtered.map((task, i) => (
            <div key={i} className={`task-item ${task.done ? 'task-done' : ''}`} onClick={() => onTaskToggle(task.meetingId, task.taskIndex)}>
              <div className={`task-checkbox ${task.done ? 'checked' : ''}`}>
                {task.done && <svg width="10" height="10" viewBox="0 0 24 24" fill="white"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" /></svg>}
              </div>
              <div className="task-content">
                <p className={`task-desc ${task.done ? 'done-text' : ''}`}>{task.description}</p>
                <div className="task-meta">
                  <span className="task-tag task-tag-meeting">{task.meetingTitle}</span>
                  {task.assignedTo && <span className="task-tag">{task.assignedTo}</span>}
                  {task.dueDate && task.dueDate !== 'null' && <span className="task-tag">{task.dueDate}</span>}
                  <span className={`task-status ${task.status?.toLowerCase()}`}>{task.status}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function CalendarView({ meetings, t, onSelectMeeting, lang }) {
  const today = new Date();
  const [viewMode, setViewMode] = useState('month');
  const [currentDate, setCurrentDate] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selectedDay, setSelectedDay] = useState(null);
  const locale = lang === 'de' ? 'de-DE' : 'en-US';

  const meetingsByDate = {};
  meetings.forEach(m => {
    const d = new Date(m.meetingDate);
    const key = `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
    if (!meetingsByDate[key]) meetingsByDate[key] = [];
    meetingsByDate[key].push(m);
  });

  const getMeetingsForDay = (year, month, day) => meetingsByDate[`${year}-${month}-${day}`] || [];

  const navigateMonth = (dir) => { setCurrentDate(prev => new Date(prev.getFullYear(), prev.getMonth() + dir, 1)); setSelectedDay(null); };
  const navigateYear = (dir) => { setCurrentDate(prev => new Date(prev.getFullYear() + dir, prev.getMonth(), 1)); setSelectedDay(null); };

  const renderMonthView = () => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const startOffset = firstDay === 0 ? 6 : firstDay - 1;
    const dayNames = lang === 'de' ? ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'] : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    const cells = [];
    for (let i = 0; i < startOffset; i++) cells.push(null);
    for (let d = 1; d <= daysInMonth; d++) cells.push(d);
    const monthName = currentDate.toLocaleDateString(locale, { month: 'long', year: 'numeric' });
    const selectedMeetings = selectedDay ? getMeetingsForDay(year, month, selectedDay) : [];

    return (
      <div className="cal-month-wrapper">
        <div className="cal-month-grid">
          <div className="cal-header">
            <button className="cal-nav-btn" onClick={() => navigateMonth(-1)}>‹</button>
            <h3 className="cal-title">{monthName}</h3>
            <button className="cal-nav-btn" onClick={() => navigateMonth(1)}>›</button>
          </div>
          <div className="cal-day-names">{dayNames.map(d => <div key={d} className="cal-day-name">{d}</div>)}</div>
          <div className="cal-grid">
            {cells.map((day, i) => {
              if (!day) return <div key={`empty-${i}`} className="cal-cell cal-cell-empty" />;
              const dayMeetings = getMeetingsForDay(year, month, day);
              const isToday = today.getFullYear() === year && today.getMonth() === month && today.getDate() === day;
              const isSelected = selectedDay === day;
              return (
                <div key={day} className={`cal-cell ${isToday ? 'cal-today' : ''} ${isSelected ? 'cal-selected' : ''} ${dayMeetings.length > 0 ? 'cal-has-meetings' : ''}`}
                  onClick={() => setSelectedDay(isSelected ? null : day)}>
                  <span className="cal-day-num">{day}</span>
                  {dayMeetings.length > 0 && (
                    <div className="cal-dots">
                      {dayMeetings.slice(0, 3).map((m, idx) => (
                        <span key={idx} className={`cal-dot ${m.aiSummary ? 'dot-analyzed' : m.protocolText ? 'dot-open' : 'dot-draft'}`} />
                      ))}
                      {dayMeetings.length > 3 && <span className="cal-dot-more">+{dayMeetings.length - 3}</span>}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
        <div className="cal-day-detail">
          {selectedDay ? (
            <>
              <h3 className="cal-detail-title">
                {t.meetingsOnDay} {new Date(currentDate.getFullYear(), currentDate.getMonth(), selectedDay).toLocaleDateString(locale, { weekday: 'long', day: 'numeric', month: 'long' })}
              </h3>
              {selectedMeetings.length === 0 ? (
                <div className="cal-no-meetings"><div style={{ fontSize: 32, marginBottom: 8 }}>📅</div><p>{t.noMeetingsOnDay}</p></div>
              ) : (
                <div className="cal-meeting-list">
                  {selectedMeetings.map(m => (
                    <div key={m.id} className="cal-meeting-item" onClick={() => onSelectMeeting(m)}>
                      <div className="cal-meeting-time">{new Date(m.meetingDate).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })}</div>
                      <div className="cal-meeting-info">
                        <span className="cal-meeting-title">{m.title}</span>
                        {m.location && <span className="cal-meeting-loc">{m.location}</span>}
                      </div>
                      <StatusBadge meeting={m} t={t} />
                    </div>
                  ))}
                </div>
              )}
            </>
          ) : (
            <div className="cal-no-meetings"><div style={{ fontSize: 32, marginBottom: 8 }}>👆</div><p>{t.selectDay}</p></div>
          )}
        </div>
      </div>
    );
  };

  const renderYearView = () => {
    const year = currentDate.getFullYear();
    const monthNames = Array.from({ length: 12 }, (_, i) => new Date(year, i, 1).toLocaleDateString(locale, { month: 'long' }));
    return (
      <div className="cal-year-wrapper">
        <div className="cal-header" style={{ background: 'transparent', border: 'none', padding: '0 0 16px 0' }}>
          <button className="cal-nav-btn" onClick={() => navigateYear(-1)}>‹</button>
          <h3 className="cal-title">{year}</h3>
          <button className="cal-nav-btn" onClick={() => navigateYear(1)}>›</button>
        </div>
        <div className="cal-year-grid">
          {monthNames.map((monthName, monthIdx) => {
            const firstDay = new Date(year, monthIdx, 1).getDay();
            const daysInMonth = new Date(year, monthIdx + 1, 0).getDate();
            const startOffset = firstDay === 0 ? 6 : firstDay - 1;
            const cells = [];
            for (let i = 0; i < startOffset; i++) cells.push(null);
            for (let d = 1; d <= daysInMonth; d++) cells.push(d);
            const monthMeetings = meetings.filter(m => { const d = new Date(m.meetingDate); return d.getFullYear() === year && d.getMonth() === monthIdx; });
            return (
              <div key={monthIdx} className="cal-mini-month" onClick={() => { setCurrentDate(new Date(year, monthIdx, 1)); setViewMode('month'); setSelectedDay(null); }}>
                <div className="cal-mini-header">
                  <span className="cal-mini-title">{monthName}</span>
                  {monthMeetings.length > 0 && <span className="cal-mini-count">{monthMeetings.length}</span>}
                </div>
                <div className="cal-mini-grid">
                  {cells.map((day, i) => {
                    if (!day) return <div key={`e-${i}`} className="cal-mini-cell" />;
                    const dayMeetings = getMeetingsForDay(year, monthIdx, day);
                    const isToday = today.getFullYear() === year && today.getMonth() === monthIdx && today.getDate() === day;
                    return (
                      <div key={day} className={`cal-mini-cell ${dayMeetings.length > 0 ? 'cal-mini-has-meeting' : ''} ${isToday ? 'cal-mini-today' : ''}`}>{day}</div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  };

  return (
    <div className="detail-panel fade-in">
      <div className="detail-header">
        <div><h2>{t.calendar}</h2><p className="detail-sub">{t.calendarSub}</p></div>
        <div className="detail-actions">
          <button className={`filter-chip ${viewMode === 'month' ? 'active' : ''}`} style={{ padding: '8px 16px' }} onClick={() => setViewMode('month')}>{t.monthView}</button>
          <button className={`filter-chip ${viewMode === 'year' ? 'active' : ''}`} style={{ padding: '8px 16px' }} onClick={() => setViewMode('year')}>{t.yearView}</button>
        </div>
      </div>
      <div className="cal-body">{viewMode === 'month' ? renderMonthView() : renderYearView()}</div>
    </div>
  );
}

function MeetingList({ meetings, selected, onSelect, search, setSearch, onNewMeeting, filter, setFilter, sort, setSort, t }) {
  const [showFilters, setShowFilters] = useState(false);
  const filtered = applyFilterAndSort(meetings, search, filter, sort);
  const groups = groupMeetingsByDate(filtered, t);
  const activeFilters = filter !== 'all' || sort !== 'date-desc';
  const FILTER_OPTIONS = [{ value: 'all', label: t.allMeetings }, { value: 'analyzed', label: t.analyzed }, { value: 'open', label: t.open }, { value: 'draft', label: t.draft }];
  const SORT_OPTIONS = [{ value: 'date-desc', label: t.sortNewest }, { value: 'date-asc', label: t.sortOldest }, { value: 'title-asc', label: t.sortTitleAZ }, { value: 'title-desc', label: t.sortTitleZA }];
  return (
    <div className="meeting-list-panel">
      <div className="list-header">
        <div className="list-header-top">
          <h2>{t.meetings} <span className="count">{meetings.length}</span></h2>
          <div style={{ display: 'flex', gap: 6 }}>
            <button className={`icon-btn ${activeFilters ? 'filter-active' : ''}`} onClick={() => setShowFilters(f => !f)} title="Filter">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z"/></svg>
            </button>
            <button className="icon-btn" onClick={onNewMeeting} title={t.newMeeting}>+</button>
          </div>
        </div>
        <div className="search-bar">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#999" strokeWidth="2"><circle cx="11" cy="11" r="8" /><path d="m21 21-4.35-4.35" /></svg>
          <input placeholder={t.searchPlaceholder} value={search} onChange={e => setSearch(e.target.value)} />
          {search && <button className="search-clear" onClick={() => setSearch('')}>×</button>}
        </div>
        {showFilters && (
          <div className="filter-panel">
            <div className="filter-group">
              <label className="filter-label">{t.status}</label>
              <div className="filter-chips">{FILTER_OPTIONS.map(o => <button key={o.value} className={`filter-chip ${filter === o.value ? 'active' : ''}`} onClick={() => setFilter(o.value)}>{o.label}</button>)}</div>
            </div>
            <div className="filter-group">
              <label className="filter-label">{t.sorting}</label>
              <select className="sort-select" value={sort} onChange={e => setSort(e.target.value)}>{SORT_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select>
            </div>
            {activeFilters && <button className="filter-reset" onClick={() => { setFilter('all'); setSort('date-desc'); }}>{t.resetFilter}</button>}
          </div>
        )}
      </div>
      <div className="meeting-items">
        {filtered.length === 0 && (
          <div className="empty-list-state">
            <div style={{ fontSize: 32, marginBottom: 12 }}>🔍</div>
            <p>{search || filter !== 'all' ? t.noMeetingsFound : t.noMeetingsYet}</p>
            {!search && filter === 'all' && <button className="btn-empty-create" onClick={onNewMeeting}>+ {t.newMeeting}</button>}
          </div>
        )}
        {Object.entries(groups).map(([label, items]) =>
          items.length === 0 ? null : (
            <div key={label}>
              <div className="date-group-label">{label}</div>
              {items.map(m => (
                <div key={m.id} className={`meeting-item slide-in ${selected?.id === m.id ? 'active' : ''}`} onClick={() => onSelect(m)}>
                  <div className="meeting-item-top"><span className="meeting-item-title">{m.title}</span><StatusBadge meeting={m} t={t} /></div>
                  <div className="meeting-item-meta">
                    <span>{m.location || (t.dashboard === 'Dashboard' ? 'Kein Ort' : 'No location')}</span>
                    <span>{new Date(m.meetingDate).toLocaleDateString(t.dashboard === 'Dashboard' ? 'de-DE' : 'en-US')}</span>
                  </div>
                  {m.protocolText && <p className="meeting-item-preview">{m.protocolText.substring(0, 65)}...</p>}
                </div>
              ))}
            </div>
          )
        )}
      </div>
    </div>
  );
}

function ProtocolTextarea({ value, onChange, t, lang }) {
  const { listening, supported, startListening, stopListening } = useSpeechRecognition((text) => { onChange(value + text); }, lang);
  return (
    <div className="protocol-textarea-wrapper">
      <textarea rows={7} placeholder={t.protocolPlaceholder} value={value} onChange={e => onChange(e.target.value)} />
      {supported && (
        <button type="button" className={`btn-mic ${listening ? 'listening' : ''}`} onClick={listening ? stopListening : startListening}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M12 14c1.66 0 3-1.34 3-3V5c0-1.66-1.34-3-3-3S9 3.34 9 5v6c0 1.66 1.34 3 3 3zm-1-9c0-.55.45-1 1-1s1 .45 1 1v6c0 .55-.45 1-1 1s-1-.45-1-1V5zm6 6c0 2.76-2.24 5-5 5s-5-2.24-5-5H5c0 3.53 2.61 6.43 6 6.92V21h2v-3.08c3.39-.49 6-3.39 6-6.92h-2z"/></svg>
          {listening ? t.stop : t.dictation}
        </button>
      )}
      {listening && <div className="mic-indicator"><span className="mic-dot" />{t.recording}</div>}
    </div>
  );
}

function ParticipantInput({ participants, setParticipants, t }) {
  const [participantInput, setParticipantInput] = useState('');
  const addParticipant = () => {
    const name = participantInput.trim();
    if (name && !participants.includes(name)) { setParticipants([...participants, name]); setParticipantInput(''); }
  };
  return (
    <div>
      <div className="participant-input-row">
        <input placeholder={t.participantPlaceholder} value={participantInput} onChange={e => setParticipantInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && addParticipant()} />
        <button type="button" className="btn-add-participant" onClick={addParticipant}>+</button>
      </div>
      {participants.length > 0 && (
        <div className="participant-chips">
          {participants.map(p => <span key={p} className="participant-chip">{p}<button onClick={() => setParticipants(participants.filter(x => x !== p))}>×</button></span>)}
        </div>
      )}
    </div>
  );
}

function NewMeetingForm({ onSave, onCancel, t, lang }) {
  const [form, setForm] = useState({ title: '', location: '', meetingDate: '', protocolText: '' });
  const [participants, setParticipants] = useState([]);
  return (
    <div className="detail-panel fade-in">
      <div className="detail-header">
        <div><h2>{t.newMeeting}</h2><p className="detail-sub">{t.newMeetingSub}</p></div>
        <div className="detail-actions">
          <button className="btn-analyze" onClick={() => { if (!form.title) return alert(t.titleLabel); onSave({ ...form, participants }); }}>{t.save}</button>
          <button className="btn-delete" onClick={onCancel}>{t.cancelEsc}</button>
        </div>
      </div>
      <div className="form-grid">
        <div className="form-group"><label>{t.titleLabel}</label><input placeholder={t.titlePlaceholder} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></div>
        <div className="form-group"><label>{t.locationLabel}</label><input placeholder={t.locationPlaceholder} value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></div>
        <div className="form-group"><label>{t.dateLabel}</label><input type="datetime-local" value={form.meetingDate} onChange={e => setForm({ ...form, meetingDate: e.target.value })} /></div>
        <div className="form-group"><label>{t.participantsLabel}</label><ParticipantInput participants={participants} setParticipants={setParticipants} t={t} /></div>
        <div className="form-group full-width"><label>{t.protocolLabel}</label><ProtocolTextarea value={form.protocolText} onChange={v => setForm({ ...form, protocolText: v })} t={t} lang={lang} /></div>
      </div>
    </div>
  );
}

function EditMeetingForm({ meeting, onSave, onCancel, t, lang }) {
  const [form, setForm] = useState({ title: meeting.title || '', location: meeting.location || '', meetingDate: meeting.meetingDate ? meeting.meetingDate.substring(0, 16) : '', protocolText: meeting.protocolText || '' });
  const [participants, setParticipants] = useState(meeting.participants || []);
  return (
    <div className="detail-panel fade-in">
      <div className="detail-header">
        <div><h2>{t.editMeeting}</h2><p className="detail-sub">{t.editSub}</p></div>
        <div className="detail-actions">
          <button className="btn-analyze" onClick={() => { if (!form.title) return alert(t.titleLabel); onSave(meeting.id, { ...form, participants }); }}>{t.save}</button>
          <button className="btn-delete" onClick={onCancel}>{t.cancel}</button>
        </div>
      </div>
      <div className="form-grid">
        <div className="form-group"><label>{t.titleLabel}</label><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></div>
        <div className="form-group"><label>{t.locationLabel}</label><input value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></div>
        <div className="form-group"><label>{t.dateLabel}</label><input type="datetime-local" value={form.meetingDate} onChange={e => setForm({ ...form, meetingDate: e.target.value })} /></div>
        <div className="form-group"><label>{t.participantsLabel}</label><ParticipantInput participants={participants} setParticipants={setParticipants} t={t} /></div>
        <div className="form-group full-width"><label>{t.protocolLabel}</label><ProtocolTextarea value={form.protocolText} onChange={v => setForm({ ...form, protocolText: v })} t={t} lang={lang} /></div>
      </div>
    </div>
  );
}

function MeetingDetail({ meeting, onAnalyze, onDelete, onEdit, analyzing, onStatusChange, onTaskToggle, onCopySummary, t }) {
  if (!meeting) {
    return (
      <div className="detail-panel empty-detail fade-in">
        <div className="empty-state"><div className="empty-icon-box">MM</div><h3>{t.noMeetingSelected}</h3><p>{t.noMeetingHint}</p></div>
      </div>
    );
  }
  return (
    <div className="detail-panel fade-in">
      <div className="detail-header">
        <div>
          <h2>{meeting.title}</h2>
          <p className="detail-sub">{meeting.location || (t.dashboard === 'Dashboard' ? 'Kein Ort' : 'No location')} &nbsp;·&nbsp; {new Date(meeting.meetingDate).toLocaleDateString(t.dashboard === 'Dashboard' ? 'de-DE' : 'en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
        <div className="detail-actions">
          <select className="status-select" value={meeting.manualStatus || 'OFFEN'} onChange={e => onStatusChange(meeting.id, e.target.value)}>
            {STATUS_OPTIONS.map(s => <option key={s} value={s}>{s.replace('_', ' ')}</option>)}
          </select>
          <button className={`btn-analyze ${analyzing ? 'loading' : ''}`} onClick={() => onAnalyze(meeting.id)} disabled={analyzing}>
            {analyzing && <span className="spinner" />}{analyzing ? t.analyzing : t.analyze}
          </button>
          <button className="btn-edit" onClick={() => onEdit(meeting)}>{t.edit}</button>
          <button className="btn-export" onClick={() => exportToPDF(meeting)}>{t.export}</button>
          <button className="btn-delete" onClick={() => onDelete(meeting.id)}>{t.delete}</button>
        </div>
      </div>
      <div className="detail-body" id="export-content">
        <div className="export-header">
          <h1 className="export-title">{meeting.title}</h1>
          <p className="export-meta">{meeting.location || ''} · {new Date(meeting.meetingDate).toLocaleDateString(t.dashboard === 'Dashboard' ? 'de-DE' : 'en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
        {meeting.participants && meeting.participants.length > 0 && (
          <div className="detail-section">
            <h3 className="section-title">{t.participants}</h3>
            <div className="participant-chips" style={{ marginTop: 0 }}>
              {meeting.participants.map(p => <span key={p} className="participant-chip participant-chip-readonly">{p}</span>)}
            </div>
          </div>
        )}
        <div className="detail-section">
          <h3 className="section-title">{t.protocol}</h3>
          <div className="protocol-box"><p>{meeting.protocolText || (t.dashboard === 'Dashboard' ? 'Kein Protokolltext vorhanden.' : 'No protocol text available.')}</p></div>
        </div>
        {meeting.aiSummary && (
          <div className="detail-section">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
              <h3 className="section-title" style={{ marginBottom: 0 }}>{t.aiSummary}</h3>
              <button className="btn-copy" onClick={() => onCopySummary(meeting.aiSummary)}>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"/></svg>
                {t.copy}
              </button>
            </div>
            <div className="ai-card"><div className="ai-card-header"><span className="ai-label">{t.geminiLabel}</span></div><p>{meeting.aiSummary}</p></div>
          </div>
        )}
        {meeting.tasks && meeting.tasks.length > 0 && (
          <div className="detail-section">
            <h3 className="section-title">{t.detectedTasks} ({meeting.tasks.filter(task => task.done).length}/{meeting.tasks.length} {t.dashboard === 'Dashboard' ? 'erledigt' : 'done'})</h3>
            <div className="task-list">
              {meeting.tasks.map((task, i) => (
                <div key={i} className={`task-item ${task.done ? 'task-done' : ''}`} onClick={() => onTaskToggle(meeting.id, i)}>
                  <div className={`task-checkbox ${task.done ? 'checked' : ''}`}>{task.done && <svg width="10" height="10" viewBox="0 0 24 24" fill="white"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" /></svg>}</div>
                  <div className="task-content">
                    <p className={`task-desc ${task.done ? 'done-text' : ''}`}>{task.description}</p>
                    <div className="task-meta">
                      {task.assignedTo && <span className="task-tag">{task.assignedTo}</span>}
                      {task.dueDate && task.dueDate !== 'null' && <span className="task-tag">{task.dueDate}</span>}
                      <span className={`task-status ${task.status?.toLowerCase()}`}>{task.status}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        <div className="export-footer"><p>MeetingMind · {new Date().toLocaleDateString(t.dashboard === 'Dashboard' ? 'de-DE' : 'en-US')}</p></div>
      </div>
    </div>
  );
}

export default function App() {
  const [showSplash, setShowSplash] = useState(!localStorage.getItem('mm_seen'));
  const [meetings, setMeetings] = useState([]);
  const [selected, setSelected] = useState(null);
  const [activeNav, setActiveNav] = useState('dashboard');
  const [showForm, setShowForm] = useState(false);
  const [editingMeeting, setEditingMeeting] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [sort, setSort] = useState('date-desc');
  const [toast, setToast] = useState(null);
  const [meetingStatuses, setMeetingStatuses] = useState(() => { try { return JSON.parse(localStorage.getItem('mm_statuses') || '{}'); } catch { return {}; } });
  const [taskStates, setTaskStates] = useState(() => { try { return JSON.parse(localStorage.getItem('mm_tasks') || '{}'); } catch { return {}; } });
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('mm_dark') === 'true');
  const [lang, setLang] = useState(() => localStorage.getItem('mm_lang') || 'de');
  const [showOnboarding, setShowOnboarding] = useState(false);
  const [showShortcuts, setShowShortcuts] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const t = TRANSLATIONS[lang];

  useEffect(() => { localStorage.setItem('mm_dark', darkMode); document.body.classList.toggle('dark', darkMode); }, [darkMode]);
  useEffect(() => { localStorage.setItem('mm_lang', lang); }, [lang]);
  useEffect(() => { localStorage.setItem('mm_statuses', JSON.stringify(meetingStatuses)); }, [meetingStatuses]);
  useEffect(() => { localStorage.setItem('mm_tasks', JSON.stringify(taskStates)); }, [taskStates]);
  useEffect(() => { loadMeetings(); }, []);

  const handleNewMeeting = useCallback(() => { setShowForm(true); setEditingMeeting(null); setActiveNav('meetings'); setSidebarOpen(false); }, []);

  useEffect(() => {
    const handleKey = (e) => {
      const tag = document.activeElement?.tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA') return;
      if (e.key === 'n' || e.key === 'N') handleNewMeeting();
      if (e.key === 'd' || e.key === 'D') { setActiveNav('dashboard'); setShowForm(false); setEditingMeeting(null); setSelected(null); }
      if (e.key === 'm' || e.key === 'M') { setActiveNav('meetings'); setShowForm(false); setEditingMeeting(null); }
      if (e.key === 't' || e.key === 'T') { setActiveNav('tasks'); setShowForm(false); setEditingMeeting(null); }
      if (e.key === 'k' || e.key === 'K') { setActiveNav('calendar'); setShowForm(false); setEditingMeeting(null); }
      if (e.key === 'l' || e.key === 'L') setLang(l => l === 'de' ? 'en' : 'de');
      if (e.key === 'Escape') { setShowForm(false); setEditingMeeting(null); setShowShortcuts(false); setSidebarOpen(false); }
      if (e.key === '?') setShowShortcuts(s => !s);
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [handleNewMeeting]);

  const showToast = (message, type = 'success') => setToast({ message, type });

  const loadMeetings = async () => {
    try {
      const res = await axios.get(API);
      const saved = JSON.parse(localStorage.getItem('mm_tasks') || '{}');
      const enriched = res.data.map(m => ({ ...m, tasks: (m.tasks || []).map((task, i) => ({ ...task, done: saved[`${m.id}-${i}`] ?? false })) }));
      setMeetings(enriched);
    } catch { showToast(t.connectionFailed, 'error'); }
  };

  const createMeeting = async (form) => {
    await axios.post(API, form);
    setShowForm(false); setActiveNav('meetings'); loadMeetings(); showToast(t.meetingCreated);
  };

  const updateMeeting = async (id, form) => {
    try { await axios.put(`${API}/${id}`, form); setEditingMeeting(null); loadMeetings(); showToast(t.meetingUpdated); setSelected(prev => prev ? { ...prev, ...form } : null); }
    catch { showToast(t.saveFailed, 'error'); }
  };

  const analyzeMeeting = async (id) => {
    setAnalyzing(true);
    try {
      const res = await axios.post(`${API}/${id}/analyze`);
      const updatedMeeting = res.data;
      const tasks = (updatedMeeting.tasks || []).map((task, i) => ({ ...task, done: taskStates[`${id}-${i}`] ?? false }));
      setSelected({ ...updatedMeeting, tasks }); loadMeetings(); showToast(t.analysisSuccess);
    } catch { showToast(t.analysisFailed, 'error'); }
    setAnalyzing(false);
  };

  const deleteMeeting = async (id) => {
    if (!window.confirm(t.confirmDelete)) return;
    await axios.delete(`${API}/${id}`); setSelected(null); loadMeetings(); showToast(t.meetingDeleted, 'info');
  };

  const handleStatusChange = (id, status) => { setMeetingStatuses(prev => ({ ...prev, [id]: status })); showToast(`${t.statusSet} "${status.replace('_', ' ')}" ${t.statusSet2}`); };

  const handleTaskToggle = (meetingId, taskIndex) => {
    const key = `${meetingId}-${taskIndex}`;
    setTaskStates(prev => { const newStates = { ...prev, [key]: !prev[key] }; localStorage.setItem('mm_tasks', JSON.stringify(newStates)); return newStates; });
    setMeetings(prev => prev.map(m => { if (m.id !== meetingId) return m; const tasks = [...(m.tasks || [])]; tasks[taskIndex] = { ...tasks[taskIndex], done: !tasks[taskIndex].done }; return { ...m, tasks }; }));
    setSelected(prev => { if (!prev || prev.id !== meetingId) return prev; const tasks = [...prev.tasks]; tasks[taskIndex] = { ...tasks[taskIndex], done: !tasks[taskIndex].done }; return { ...prev, tasks }; });
  };

  const handleCopySummary = (text) => { navigator.clipboard.writeText(text).then(() => showToast(t.copied)); };

  const enrichedSelected = selected ? { ...selected, manualStatus: meetingStatuses[selected.id] || 'OFFEN' } : null;

  const renderMain = () => {
    if (showForm) return <NewMeetingForm key="form" onSave={createMeeting} onCancel={() => setShowForm(false)} t={t} lang={lang} />;
    if (editingMeeting) return <EditMeetingForm key={`edit-${editingMeeting.id}`} meeting={editingMeeting} onSave={updateMeeting} onCancel={() => setEditingMeeting(null)} t={t} lang={lang} />;
    if (activeNav === 'dashboard') return <Dashboard key="dashboard" meetings={meetings} t={t} />;
    if (activeNav === 'tasks') return <TasksOverview key="tasks" meetings={meetings} onTaskToggle={handleTaskToggle} t={t} />;
    if (activeNav === 'calendar') return <CalendarView key="calendar" meetings={meetings} t={t} lang={lang} onSelectMeeting={(m) => { const tasks = (m.tasks || []).map((task, i) => ({ ...task, done: taskStates[`${m.id}-${i}`] ?? task.done ?? false })); setSelected({ ...m, tasks }); setActiveNav('meetings'); }} />;
    return <MeetingDetail key={selected?.id || 'empty'} meeting={enrichedSelected} onAnalyze={analyzeMeeting} onDelete={deleteMeeting} onEdit={(m) => setEditingMeeting(m)} analyzing={analyzing} onStatusChange={handleStatusChange} onTaskToggle={handleTaskToggle} onCopySummary={handleCopySummary} t={t} />;
  };

  if (showSplash) {
    return <SplashScreen onDone={() => { localStorage.setItem('mm_seen', 'true'); setShowSplash(false); if (!localStorage.getItem('mm_onboarded')) setShowOnboarding(true); }} />;
  }

  return (
    <>
      {showOnboarding && <OnboardingScreen t={t} onFinish={() => { localStorage.setItem('mm_onboarded', 'true'); setShowOnboarding(false); }} />}
      {showShortcuts && <ShortcutsModal onClose={() => setShowShortcuts(false)} t={t} />}
      <div className="app-layout">
        {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
        <button className="mobile-menu-btn" onClick={() => setSidebarOpen(true)}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/></svg>
        </button>
        <Sidebar activeNav={activeNav} setActiveNav={(nav) => { setActiveNav(nav); setShowForm(false); setEditingMeeting(null); setSelected(null); }} onNewMeeting={handleNewMeeting} darkMode={darkMode} setDarkMode={setDarkMode} sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} t={t} lang={lang} setLang={setLang} />
        <MeetingList meetings={meetings} selected={selected} onSelect={(m) => { const tasks = (m.tasks || []).map((task, i) => ({ ...task, done: taskStates[`${m.id}-${i}`] ?? task.done ?? false })); setSelected({ ...m, tasks }); setShowForm(false); setEditingMeeting(null); setActiveNav('meetings'); }} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} sort={sort} setSort={setSort} onNewMeeting={handleNewMeeting} t={t} />
        {renderMain()}
        <button className="shortcuts-hint" onClick={() => setShowShortcuts(true)} title="?">?</button>
      </div>
    </>
  );
}